create table Archive_of_books (
	book_ID INTEGER,
	title VARCHAR(50),
	author VARCHAR(50),
	foreign key (book_ID) references Books_1(book_ID)
);
insert into Archive_of_books (book_ID, title, author) values (984325892, '2046', 'Ricky Hickisson');
insert into Archive_of_books (book_ID, title, author) values (190554571, 'Henry V', 'Hakeem Eby');
insert into Archive_of_books (book_ID, title, author) values (606388644, 'Manta - Der Film', 'Harper Lidgely');
insert into Archive_of_books (book_ID, title, author) values (682418412, 'Beyond the Door II (Schock) (Shock) (Suspense)', 'Joaquin Domerque');
insert into Archive_of_books (book_ID, title, author) values (602025574, 'The D.I.', 'Latrena Bril');
insert into Archive_of_books (book_ID, title, author) values (871394477, 'Matrix, The', 'Stavros Grasha');
insert into Archive_of_books (book_ID, title, author) values (266104107, 'Adult Camp', 'Korey Churchouse');
insert into Archive_of_books (book_ID, title, author) values (674637828, 'Clara''s Heart', 'Frederic Cormode');
insert into Archive_of_books (book_ID, title, author) values (692690513, 'Merchant of Venice, The', 'Kilian Selcraig');
insert into Archive_of_books (book_ID, title, author) values (292757655, 'Cookers', 'Ginnie Styan');
insert into Archive_of_books (book_ID, title, author) values (300086305, 'Strip-tease', 'Wilt Ricoald');
insert into Archive_of_books (book_ID, title, author) values (624254728, 'Never Say Never Again', 'Concettina Hallows');
insert into Archive_of_books (book_ID, title, author) values (059306294, 'Toy Story Toons: Small Fry', 'Nickie Gregoraci');
insert into Archive_of_books (book_ID, title, author) values (155125264, 'Club Sandwich', 'Roderick Gyorffy');
insert into Archive_of_books (book_ID, title, author) values (151239935, 'Eighth Day, The (Den Åttonde dagen)', 'Rollins Canner');
insert into Archive_of_books (book_ID, title, author) values (928679304, 'Invisible Woman, The', 'Godfrey Burtt');
insert into Archive_of_books (book_ID, title, author) values (671179844, 'I Love You, I Love You Not', 'Ruth Croix');
insert into Archive_of_books (book_ID, title, author) values (630481944, 'Den tatuerade änkan (Tattooed Widow, The) ', 'Rheta Burney');
insert into Archive_of_books (book_ID, title, author) values (574812879, 'A Fight For', 'Elvera Wornum');
insert into Archive_of_books (book_ID, title, author) values (123760379, 'Place in the Sun, A (En plats i solen)', 'Carma Whitesel');
insert into Archive_of_books (book_ID, title, author) values (850633309, 'Confidential Agent', 'Valentina Wesson');
insert into Archive_of_books (book_ID, title, author) values (213771854, 'Two of Us, The (Le vieil homme et l''enfant)', 'Leanna Von Gladbach');
insert into Archive_of_books (book_ID, title, author) values (273347728, 'Careful', 'Pauly Daniele');
insert into Archive_of_books (book_ID, title, author) values (278874058, 'Raise the Red Lantern (Da hong deng long gao gao gua)', 'Scarlett Domesday');
insert into Archive_of_books (book_ID, title, author) values (748991605, 'Star Trek: First Contact', 'Lukas Russan');
insert into Archive_of_books (book_ID, title, author) values (749454050, 'Dog Soldiers', 'Sayer Croxford');
insert into Archive_of_books (book_ID, title, author) values (709997951, 'Walker', 'Ginger Gilhoolie');
insert into Archive_of_books (book_ID, title, author) values (692729646, 'Virginia''s Run', 'Claiborne Tague');
insert into Archive_of_books (book_ID, title, author) values (977409441, 'Mahakaal (The Monster)', 'Dael Borrill');
insert into Archive_of_books (book_ID, title, author) values (510664525, 'Food of the Gods II', 'Austin Mayes');
insert into Archive_of_books (book_ID, title, author) values (748649528, 'Downstairs', 'Tanny Candy');
insert into Archive_of_books (book_ID, title, author) values (848719791, 'Closure', 'Anjanette Ellaman');
insert into Archive_of_books (book_ID, title, author) values (134539574, 'Suicide Manual (Jisatsu manyaru)', 'Merwin Pacher');
insert into Archive_of_books (book_ID, title, author) values (332843880, 'Monty Python''s The Meaning of Life', 'Meredeth Huburn');
insert into Archive_of_books (book_ID, title, author) values (754089716, 'Schindler''s List', 'Ellwood Wakeley');
insert into Archive_of_books (book_ID, title, author) values (042409098, 'On a marché sur Bangkok', 'Rina Ryan');
insert into Archive_of_books (book_ID, title, author) values (339784824, 'Sound of My Voice', 'Morgana Adanez');
insert into Archive_of_books (book_ID, title, author) values (773552443, 'Kite Runner, The', 'Maritsa Bullier');
insert into Archive_of_books (book_ID, title, author) values (350167891, 'Queen of Blood', 'Pedro Jadczak');
insert into Archive_of_books (book_ID, title, author) values (847163693, 'Confessions of a Dangerous Mind', 'Renard Reedman');
insert into Archive_of_books (book_ID, title, author) values (456654737, 'One Point O', 'Melodee Christin');
insert into Archive_of_books (book_ID, title, author) values (033391266, 'Pépé le Moko', 'Wang Auden');
insert into Archive_of_books (book_ID, title, author) values (083537150, 'Ghosts of Mississippi', 'Guenevere Dellatorre');
insert into Archive_of_books (book_ID, title, author) values (224608245, 'Feast II: Sloppy Seconds', 'Lanie de Leon');
insert into Archive_of_books (book_ID, title, author) values (479911258, 'Arrival of a Train, The', 'Gustavo Cottee');
insert into Archive_of_books (book_ID, title, author) values (594689417, 'Pressure Point ', 'Dagmar Sherrard');
insert into Archive_of_books (book_ID, title, author) values (872106363, 'Romance in a Minor Key (Romanze in Moll)', 'Cornie Whiston');
insert into Archive_of_books (book_ID, title, author) values (543053958, 'American Ninja 3: Blood Hunt', 'Lian Fraschetti');
insert into Archive_of_books (book_ID, title, author) values (812251015, '711 Ocean Drive', 'Gordie Rowat');
insert into Archive_of_books (book_ID, title, author) values (166323003, 'Missing in America', 'Kendre Shobbrook');
insert into Archive_of_books (book_ID, title, author) values (202887732, 'Back Door to Hell', 'Newton Lamminam');
insert into Archive_of_books (book_ID, title, author) values (011854319, 'Saint Jack', 'Hyman Paulsen');
insert into Archive_of_books (book_ID, title, author) values (842476497, 'Burning Bright', 'Fenelia Le Provost');
insert into Archive_of_books (book_ID, title, author) values (794439718, 'Crash', 'Bridgette Dallimore');
insert into Archive_of_books (book_ID, title, author) values (369111992, 'Tables Turned on the Gardener', 'Celinda Burress');
insert into Archive_of_books (book_ID, title, author) values (400106251, 'Burke and Hare', 'Hugh Fidelli');
insert into Archive_of_books (book_ID, title, author) values (134711074, 'Don''t You Forget About Me', 'Darcy Eliassen');
insert into Archive_of_books (book_ID, title, author) values (762020748, 'All Dogs Christmas Carol, An', 'Sheff Wildblood');
insert into Archive_of_books (book_ID, title, author) values (410159957, 'High Noon', 'Micheil Empson');
insert into Archive_of_books (book_ID, title, author) values (176126159, 'Thunderheart', 'Pat Beteriss');
insert into Archive_of_books (book_ID, title, author) values (655942607, 'Confessor, The (a.k.a. The Good Shepherd)', 'Elianora Hodcroft');
insert into Archive_of_books (book_ID, title, author) values (154513272, 'Terror, The', 'Ava Grewe');
insert into Archive_of_books (book_ID, title, author) values (237918465, 'Ingmar Bergman on Life and Work (Ingmar Bergman: Om liv och arbete)', 'Max Newbatt');
insert into Archive_of_books (book_ID, title, author) values (296196338, 'Fred & Vinnie', 'Tawsha McCotter');
insert into Archive_of_books (book_ID, title, author) values (665313868, 'Fat Man and Little Boy', 'Melvin Skittrell');
insert into Archive_of_books (book_ID, title, author) values (392494285, 'Eye of the Dolphin', 'Edin Studdert');
insert into Archive_of_books (book_ID, title, author) values (401440659, 'My Life as McDull (Mak dau goo si)', 'Felike De Hailes');
insert into Archive_of_books (book_ID, title, author) values (921365754, 'Killer of Sheep', 'Pavlov Fillon');
insert into Archive_of_books (book_ID, title, author) values (194043986, 'Pups', 'Lida Shutt');
insert into Archive_of_books (book_ID, title, author) values (357119243, 'Mrs. Dalloway', 'Shawna Johnsee');
insert into Archive_of_books (book_ID, title, author) values (934843284, 'Dick Tracy', 'Efrem Pierucci');
insert into Archive_of_books (book_ID, title, author) values (025843064, 'Deluge, The (Potop)', 'Marie-jeanne Stoppe');
insert into Archive_of_books (book_ID, title, author) values (441070236, 'Bandits', 'Josephine Ramet');
insert into Archive_of_books (book_ID, title, author) values (183479879, 'T,O,U,C,H,I,N,G', 'Halette Habergham');
insert into Archive_of_books (book_ID, title, author) values (728632402, 'Exterminating Angel, The (Ángel exterminador, El)', 'Tracey Clee');
insert into Archive_of_books (book_ID, title, author) values (185311413, 'Who Killed Nancy?', 'Alwin Conduit');
insert into Archive_of_books (book_ID, title, author) values (733095017, 'Girlfriend Experience, The', 'Hendrik Doulton');
insert into Archive_of_books (book_ID, title, author) values (105985692, 'Homefront', 'Margarethe Kirkwood');
insert into Archive_of_books (book_ID, title, author) values (850642364, 'Visitor to a Museum (Posetitel muzeya)', 'Had Bax');
insert into Archive_of_books (book_ID, title, author) values (061796408, 'Snipes', 'Armstrong Gilding');
insert into Archive_of_books (book_ID, title, author) values (238463518, 'Mad City', 'Virgil Pateman');
insert into Archive_of_books (book_ID, title, author) values (821372872, 'Wolfman, The', 'Meghan Velden');
insert into Archive_of_books (book_ID, title, author) values (919545824, 'Arabesque', 'Millie Caghan');
insert into Archive_of_books (book_ID, title, author) values (551003688, 'Shipping News, The', 'Aubine East');
insert into Archive_of_books (book_ID, title, author) values (953391921, 'Wings in the Dark', 'Gradeigh Cassey');
insert into Archive_of_books (book_ID, title, author) values (164412009, 'Capricorn One', 'Teodoor Danes');
insert into Archive_of_books (book_ID, title, author) values (164873747, 'Bikini Beach', 'Shannon Housley');
insert into Archive_of_books (book_ID, title, author) values (934560497, 'Crazy, Stupid, Love.', 'Bobbie Watson-Brown');
insert into Archive_of_books (book_ID, title, author) values (309816652, 'Passing Strange', 'Aloise Lobley');
insert into Archive_of_books (book_ID, title, author) values (798894595, 'Return to Me', 'Marysa Makinson');
insert into Archive_of_books (book_ID, title, author) values (899174971, 'Kid Stays in the Picture, The', 'Conrade Towers');
insert into Archive_of_books (book_ID, title, author) values (909915488, 'Dante''s Peak', 'Jillana Gaythor');
insert into Archive_of_books (book_ID, title, author) values (864154212, 'Candyman: Farewell to the Flesh', 'Alla Pinckard');
insert into Archive_of_books (book_ID, title, author) values (077651274, 'Sympathy for the Devil', 'Shaylyn Joret');
insert into Archive_of_books (book_ID, title, author) values (151871370, 'Palestine Is Still the Issue', 'Thorin Cromer');
insert into Archive_of_books (book_ID, title, author) values (986817425, 'Angel-A', 'Giulio Dhennin');
insert into Archive_of_books (book_ID, title, author) values (116167241, 'Polyester', 'Ronald Gerrets');
insert into Archive_of_books (book_ID, title, author) values (402993143, 'Belle', 'Teresita Badder');
insert into Archive_of_books (book_ID, title, author) values (508159979, 'Talk to Her (Hable con Ella)', 'Zia Solan');
insert into Archive_of_books (book_ID, title, author) values (942623667, 'Extraordinary Adventures of Adèle Blanc-Sec, The', 'Lin Moro');
