create table Publisher (
	publisher_ID INT primary key,
	publisher_name VARCHAR(50)
);
insert into Publisher (publisher_ID, publisher_name) values (2001, 'PHENADOZ');
insert into Publisher (publisher_ID, publisher_name) values (2002, 'Oxycodone Hydrochloride');
insert into Publisher (publisher_ID, publisher_name) values (2003, 'Australian Gold');
insert into Publisher (publisher_ID, publisher_name) values (2004, 'Capex');
insert into Publisher (publisher_ID, publisher_name) values (2005, 'DIARRHEA VOMITING');
insert into Publisher (publisher_ID, publisher_name) values (2006, 'Necon 10/11');
insert into Publisher (publisher_ID, publisher_name) values (2007, 'Nortriptyline Hydrochloride');
insert into Publisher (publisher_ID, publisher_name) values (2008, 'Phenytoin Sodium');
insert into Publisher (publisher_ID, publisher_name) values (2009, 'Loratadine ODT');
insert into Publisher (publisher_ID, publisher_name) values (2010, 'IPKN Moist and Firm BB 01 Light');
insert into Publisher (publisher_ID, publisher_name) values (2011, 'ORAL-DENT');
insert into Publisher (publisher_ID, publisher_name) values (2012, 'SSKI');
insert into Publisher (publisher_ID, publisher_name) values (2013, 'GM Collin Mineral Sun');
insert into Publisher (publisher_ID, publisher_name) values (2014, 'Hydroxychloroquine Sulfate');
insert into Publisher (publisher_ID, publisher_name) values (2015, 'Night Time Sinus');
insert into Publisher (publisher_ID, publisher_name) values (2016, 'Pramipexole Dihydrochloride');
insert into Publisher (publisher_ID, publisher_name) values (2017, 'SOLU-MEDROL');
insert into Publisher (publisher_ID, publisher_name) values (2018, 'Citalopram');
insert into Publisher (publisher_ID, publisher_name) values (2019, 'SHISEIDO SHEER MATIFYING COMPACT (REFILL)');
insert into Publisher (publisher_ID, publisher_name) values (2020, 'Western Ragweed');
insert into Publisher (publisher_ID, publisher_name) values (2021, 'NITROUS OXIDE');
insert into Publisher (publisher_ID, publisher_name) values (2022, 'Lindane');
insert into Publisher (publisher_ID, publisher_name) values (2023, 'Levothyroxine Sodium');
insert into Publisher (publisher_ID, publisher_name) values (2024, 'Isuprel');
insert into Publisher (publisher_ID, publisher_name) values (2025, 'mally Poreless Perfection Glowing Foundation Rich');
insert into Publisher (publisher_ID, publisher_name) values (2026, 'Lamotrigine');
insert into Publisher (publisher_ID, publisher_name) values (2027, 'nevirapine');
insert into Publisher (publisher_ID, publisher_name) values (2028, 'risperidone');
insert into Publisher (publisher_ID, publisher_name) values (2029, 'Donnatal');
insert into Publisher (publisher_ID, publisher_name) values (2030, 'HYDROCORTISONE');
insert into Publisher (publisher_ID, publisher_name) values (2031, 'Rye Grain');
insert into Publisher (publisher_ID, publisher_name) values (2032, 'MUCOSA DM');
insert into Publisher (publisher_ID, publisher_name) values (2033, 'Petroleum Kit Refill');
insert into Publisher (publisher_ID, publisher_name) values (2034, 'FreshKote Lubricant Eye Drops');
insert into Publisher (publisher_ID, publisher_name) values (2035, 'Olive');
insert into Publisher (publisher_ID, publisher_name) values (2036, 'Hydration Complex');
insert into Publisher (publisher_ID, publisher_name) values (2037, 'Sunbrellas Family Sunblock SPF 45');
insert into Publisher (publisher_ID, publisher_name) values (2038, 'Nivea A Kiss of Smoothness Lip Care');
insert into Publisher (publisher_ID, publisher_name) values (2039, 'OXY Daily Defense Advanced Facial Cleanser');
insert into Publisher (publisher_ID, publisher_name) values (2040, 'Indomethacin');
insert into Publisher (publisher_ID, publisher_name) values (2041, 'Hydrogen Peroxide');
insert into Publisher (publisher_ID, publisher_name) values (2042, 'REMERONSOLTAB');
insert into Publisher (publisher_ID, publisher_name) values (2043, 'Olay Fresh Effects');
insert into Publisher (publisher_ID, publisher_name) values (2044, 'Glandulae suprarenales 6');
insert into Publisher (publisher_ID, publisher_name) values (2045, 'Atorvastatin Calcium');
insert into Publisher (publisher_ID, publisher_name) values (2046, 'Sulfasalazine');
insert into Publisher (publisher_ID, publisher_name) values (2047, 'Ropinirole Hydrochloride');
insert into Publisher (publisher_ID, publisher_name) values (2048, 'Diclofenac Sodium');
insert into Publisher (publisher_ID, publisher_name) values (2049, 'FNG');
insert into Publisher (publisher_ID, publisher_name) values (2050, 'Oxygen');
insert into Publisher (publisher_ID, publisher_name) values (2051, 'Sheer Genius Liquid Foundation - Medium Look');
insert into Publisher (publisher_ID, publisher_name) values (2052, 'Cepacol');
insert into Publisher (publisher_ID, publisher_name) values (2053, 'Triamterene and Hydrochlorothiazide');
insert into Publisher (publisher_ID, publisher_name) values (2054, 'Derma 1 Healthcare Hand Wash');
insert into Publisher (publisher_ID, publisher_name) values (2055, 'Loperamide Hydrochloride');
insert into Publisher (publisher_ID, publisher_name) values (2056, 'Metformin Hydrochloride');
insert into Publisher (publisher_ID, publisher_name) values (2057, 'CARE ONE');
insert into Publisher (publisher_ID, publisher_name) values (2058, 'Enalapril Maleate');
insert into Publisher (publisher_ID, publisher_name) values (2059, 'Aclovate');
insert into Publisher (publisher_ID, publisher_name) values (2060, 'FORTOLIN');
insert into Publisher (publisher_ID, publisher_name) values (2061, 'ELOCTATE');
insert into Publisher (publisher_ID, publisher_name) values (2062, 'Brompheniramine Pseudoephedrine DM');
insert into Publisher (publisher_ID, publisher_name) values (2063, 'PANROSA Rose Scented Hand');
insert into Publisher (publisher_ID, publisher_name) values (2064, 'Topamax');
insert into Publisher (publisher_ID, publisher_name) values (2065, 'AcneWorx');
insert into Publisher (publisher_ID, publisher_name) values (2066, 'iBaba');
insert into Publisher (publisher_ID, publisher_name) values (2067, 'ANTIVENIN');
insert into Publisher (publisher_ID, publisher_name) values (2068, 'Hydromorphone HCl');
insert into Publisher (publisher_ID, publisher_name) values (2069, 'Penicillin V Potassium');
insert into Publisher (publisher_ID, publisher_name) values (2070, 'Hydrocodone Bitartrate and Acetaminophen');
insert into Publisher (publisher_ID, publisher_name) values (2071, 'Acetaminophen PM');
insert into Publisher (publisher_ID, publisher_name) values (2072, 'EZ2go');
insert into Publisher (publisher_ID, publisher_name) values (2073, 'Hot Spot');
insert into Publisher (publisher_ID, publisher_name) values (2074, 'Homeopathic Constipation Relief');
insert into Publisher (publisher_ID, publisher_name) values (2075, 'Eve Lom Radiance Lift Foundation SPF 15');
insert into Publisher (publisher_ID, publisher_name) values (2076, 'Ponderosa Pine');
insert into Publisher (publisher_ID, publisher_name) values (2077, 'Ladys Choice Invisible Solid');
insert into Publisher (publisher_ID, publisher_name) values (2078, 'ibuprofen pm');
insert into Publisher (publisher_ID, publisher_name) values (2079, 'Keppra');
insert into Publisher (publisher_ID, publisher_name) values (2080, 'Intervene Radiance Boosting Moisture SPF 15');
insert into Publisher (publisher_ID, publisher_name) values (2081, 'TRETIN.X');
insert into Publisher (publisher_ID, publisher_name) values (2082, 'Citalopram Hydrobromide');
insert into Publisher (publisher_ID, publisher_name) values (2083, 'Aveeno Daily Moisturizing');
insert into Publisher (publisher_ID, publisher_name) values (2084, 'cough');
insert into Publisher (publisher_ID, publisher_name) values (2085, 'Levofloxacin');
insert into Publisher (publisher_ID, publisher_name) values (2086, 'Methylphenidate Hydrochloride');
insert into Publisher (publisher_ID, publisher_name) values (2087, 'LBEL EFET PARFAIT Spots Reducing Effect Foundation SPF 18 - MEDIUM 5');
insert into Publisher (publisher_ID, publisher_name) values (2088, 'Simvastatin');
insert into Publisher (publisher_ID, publisher_name) values (2089, 'No7 Soft and Sheer Tinted Moisturiser Dark');
insert into Publisher (publisher_ID, publisher_name) values (2090, 'Minocycline Hydrochloride');
insert into Publisher (publisher_ID, publisher_name) values (2091, 'Rite Aid Acne Pads, Daily Cleansing Pads');
insert into Publisher (publisher_ID, publisher_name) values (2092, 'Potassium Chloride in Dextrose and Sodium Chloride');
insert into Publisher (publisher_ID, publisher_name) values (2093, 'HAEMONETICS 0.9 % Sodium Chloride');
insert into Publisher (publisher_ID, publisher_name) values (2094, 'Purell Advanced Hand Sanitizer Refreshing Florals');
insert into Publisher (publisher_ID, publisher_name) values (2095, 'PURE SHEER');
insert into Publisher (publisher_ID, publisher_name) values (2096, 'C Lax Laxative');
insert into Publisher (publisher_ID, publisher_name) values (2097, 'CENTER-AL - PLANTAGO LANCEOLATA POLLEN');
insert into Publisher (publisher_ID, publisher_name) values (2098, 'Benztropine Mesylate');
insert into Publisher (publisher_ID, publisher_name) values (2099, 'biclora-D');
insert into Publisher (publisher_ID, publisher_name) values (2100, 'ILLUMINATING DAILY MOISTURIZER');
