create table Requests (
	title VARCHAR(50),
	author VARCHAR(50),
	user_email VARCHAR(50),
	foreign key(user_email) references Students(email),
	foreign key(user_email) references Teachers(email)
);
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'carnfield0@elpais.c');
insert into Requests (title, author, user_email) values ('Vares: The Path of the Righteous Men (Vares - Kaidan tien kulkijat)', 'Brooks Bennedick', 'ktoohey1a@reference.c');
insert into Requests (title, author, user_email) values ('In Gold We Trust (600 kilos d''or pur)', 'Kyla Hyett', 'grubinowiczf@hc360.c');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'cbradlaugh1c@aol.c');
insert into Requests (title, author, user_email) values ('Come Dance with Me!', 'Starr Gaynor', 'mvispo4@infoseek.co.');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton',  'mwhitlock1e@dailymotion.c');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'jwethers6@dailymail.co.');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'phaack1g@amazon.de');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'jblackabyl@qq.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'jharner1i@oaic.gov.au');
insert into Requests (title, author, user_email) values ('When the Wind Blows', 'Alejandro Dries', 'cbenticka@wix.com');
insert into Requests (title, author, user_email) values ('Burglar', 'Sharlene Bilbrey', 'gringer1k@state.tx.us');
insert into Requests (title, author, user_email) values ('Superhero Movie', 'Mirelle Durden', 'cmeiklamc@tripadvisor.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'shiggen1m@sina.com.cn');
insert into Requests (title, author, user_email) values ('Felix the Cat: The Movie', 'Ode Dutt', 'tlalorr@slashdot.org');
insert into Requests (title, author, user_email) values ('Amen.', 'Alic Blaza',  'rcordeiro1o@theatlantic.com');
insert into Requests (title, author, user_email) values ('Hijacking, A (Kapringen)', 'Rosaline Wagenen', 'ajohnceyg@toplist.cz');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'trembrandt1q@ftc.gov');
insert into Requests (title, author, user_email) values ('White Fang', 'Waly Dusting', 'smilksopi@rediff.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'orubel1s@mapquest.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'nbreffitx@mac.com');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'nprin1u@yandex.ru');
insert into Requests (title, author, user_email) values ('Amen.', 'Alic Blaza', 'kjacobowitsm@google.com.hk');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'tblakden1w@dyndns.org');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'pkaino@hatena.ne.jp');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton',  'vkitteridge1y@sourceforge.net');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'ssheward13@msu.edu');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton',  'apapworth20@moonfruit.com');
insert into Requests (title, author, user_email) values ('Amen.', 'Alic Blaza',  'gkenners@phpbb.com');
insert into Requests (title, author, user_email) values ('Tropico', 'Ange Creasey', 'zfitchell22@craigslist.org');
insert into Requests (title, author, user_email) values ('Twilight Saga: Breaking Dawn - Part 2, The', 'Tobiah Mickleburgh',  'fapsu@aboutads.info');
insert into Requests (title, author, user_email) values ('Laugh, Clown, Laugh', 'Felice Grayley', 'tdarrington24@hp.com');
insert into Requests (title, author, user_email) values ('Begin Again', 'Jeremiah Pruvost', 'sprestner19@exblog.jp');
insert into Requests (title, author, user_email) values ('Storm Rider', 'Hyacintha Mapstone',  'mdightham26@wp.com');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'mwinneyy@eepurl.com');
insert into Requests (title, author, user_email) values ('Amen.', 'Alic Blaza', 'tphoebe28@zimbio.com');
insert into Requests (title, author, user_email) values ('Amen.', 'Alic Blaza', 'rygo10@noaa.gov');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton',  'mbramhall2a@psu.edu');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'psmittoune1f@mayoclinic.com');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'cmattielli2c@wiley.com');
insert into Requests (title, author, user_email) values ('Narrien illat ', 'Becca Woodvine',  'kdelwater14@slate.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'cparlet2e@ed.gov');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'pewbanks16@purevolume.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead',  'mprue2g@accuweather.com');
insert into Requests (title, author, user_email) values ('Shadows', 'Ariella Hooke', 'cbisp1l@nifty.com');
insert into Requests (title, author, user_email) values ('Shadows', 'Ariella Hooke',  'wmcgeffen2i@sfgate.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'ktoohey1a@reference.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'rroos2k@dion.ne.jp');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'cbradlaugh1c@aol.com');
insert into Requests (title, author, user_email) values ('Shadows', 'Ariella Hooke', 'lplumstead2m@tinyurl.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'dboundey1r@msn.com');
insert into Requests (title, author, user_email) values ('Saturday Night Fever', 'Bathsheba Jolliff', 'arisdale2o@huffingtonpost.com');
insert into Requests (title, author, user_email) values ('Shadows', 'Ariella Hooke',  'phaack1g@amazon.de');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead',  'npetren2q@t-online.de');
insert into Requests (title, author, user_email) values ('Shadows', 'Ariella Hooke', 'jharner1i@oaic.gov.au');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'mbernhardt0@t.co');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'mlewnden1x@networksolutions.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'tleather2@adobe.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'shiggen1m@sina.com.cn');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'ocrompton4@tripadvisor.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear',  'rcordeiro1o@theatlantic.com');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'rpurdy6@desdev.cn');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'nbrack23@unblog.fr');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'sdiruggero8@cargocollective.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'orubel1s@mapquest.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'ccosgrya@g.co');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'nprin1u@yandex.ru');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'psawlc@goo.gl');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'zmcclosh29@businessweek.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'mpalmare@github.io');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'vkitteridge1y@sourceforge.net');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'fbestwallg@paginegialle.it');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'apapworth20@moonfruit.com');
insert into Requests (title, author, user_email) values ('Blood and Sand', 'Weylin Coye', 'mjorckei@wikispaces.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'mmartyntsev2f@hp.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'jtrudgionk@zimbio.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'tdarrington24@hp.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'tglayzerm@jigsy.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear',  'mdightham26@wp.com');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'aiacopinio@rakuten.co.jp');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'aroyl2l@irs.gov');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'jtwiddleq@msn.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'mbramhall2a@psu.edu');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'ghancills@si.edu');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'cmattielli2c@wiley.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'dmcnaughtu@mapy.cz');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'kenga2r@1und1.de');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'nandrysw@sbwire.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'mprue2g@accuweather.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'xsabatery@networksolutions.com');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'wmcgeffen2i@sfgate.com');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'miacovini10@etsy.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'dkelcher5@rediff.com');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'bortner12@addthis.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'lplumstead2m@tinyurl.com');
insert into Requests (title, author, user_email) values ('Grotesque', 'Shellie Unstead', 'jkuzemka14@youtu.be');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'arisdale2o@huffingtonpost.com');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'smoynihan16@dell.com');
insert into Requests (title, author, user_email) values ('Times and Winds (Bes vakit)', 'Lucien Mennear', 'bstoreyb@cbc.ca');
insert into Requests (title, author, user_email) values ('Captain Phillips', 'Elysee Dolton', 'mlively18@utexas.edu');
